"""Reference research seed — a curated, pre-authored knowledge base covering
the major model families in the OpenRouter catalog and the local Ollama
ecosystem, so the registry is useful immediately instead of mostly empty, and
so every future research/manual entry has hundreds of consistently-formatted
examples to match ("what done-well looks like" for tags, tier, and good_for
phrasing).

PROVENANCE, stated plainly: these are knowledge-based estimates authored by
Claude Fable 5 (knowledge cutoff Jan 2026) when this dataset was generated —
not live benchmark lookups. Every score lands as score_type="estimated" with
moderate confidence and source_url "reference-seed:fable-5-2026-07", and the
loader (reference_seed.py) NEVER overwrites manual overrides, Research Agent
results, or existing benchmark rows. Real data always wins over this file.

Entry format:
  match:   lowercase substrings matched against model ids (OpenRouter
           "vendor/name" ids and bare Ollama tags alike); the longest match
           across all entries wins, so specific entries beat family entries.
  tags:    subset of the shared vocabulary (registry/tagging.py).
  scores:  0-100 per benchmark category, my rough estimate of where the
           family sits relative to the field.
"""

# Categories: coding | reasoning | general_chat | tool_calling | agentic
REFERENCE_SEED = [
    # ---- Anthropic ----------------------------------------------------------
    {"match": ["claude-fable", "claude-mythos"],
     "tags": ["coding", "reasoning", "tool-calling", "long-context"],
     "relative_cost_tier": "very_high",
     "good_for": "hardest reasoning, large multi-file architecture, long agentic runs, final review passes",
     "reasoning_style": "frontier-tier deliberate planner; strongest at long-horizon agentic work",
     "refine": False, "confidence": 0.6,
     "scores": {"coding": 97, "reasoning": 97, "general_chat": 95, "tool_calling": 96, "agentic": 97}},
    {"match": ["claude-opus"],
     "tags": ["coding", "reasoning", "tool-calling", "long-context"],
     "relative_cost_tier": "high",
     "good_for": "complex architecture, deep multi-file coding, hard reasoning, code review",
     "reasoning_style": "deliberate and thorough; plans before acting, excellent agentic persistence",
     "refine": False, "confidence": 0.6,
     "scores": {"coding": 93, "reasoning": 93, "general_chat": 92, "tool_calling": 93, "agentic": 93}},
    {"match": ["claude-sonnet"],
     "tags": ["coding", "reasoning", "tool-calling", "long-context"],
     "relative_cost_tier": "medium",
     "good_for": "day-to-day strong coding, agentic tool use, balanced cost/quality escalation target",
     "reasoning_style": "fast, pragmatic, reliably-structured; the workhorse tier",
     "refine": False, "confidence": 0.6,
     "scores": {"coding": 90, "reasoning": 88, "general_chat": 89, "tool_calling": 91, "agentic": 90}},
    {"match": ["claude-haiku"],
     "tags": ["coding", "tool-calling"],
     "relative_cost_tier": "low",
     "good_for": "fast cheap chat, light coding, high-volume tool calls, summarization",
     "reasoning_style": "quick and direct; weaker on deep multi-step reasoning",
     "refine": False, "confidence": 0.6,
     "scores": {"coding": 78, "reasoning": 75, "general_chat": 82, "tool_calling": 84, "agentic": 76}},

    # ---- OpenAI -------------------------------------------------------------
    {"match": ["gpt-5-codex", "gpt-5.1-codex"],
     "tags": ["coding", "tool-calling"],
     "good_for": "dedicated coding/agentic-editing workloads",
     "reasoning_style": "code-specialized planner tuned for long editing sessions",
     "refine": False, "confidence": 0.55,
     "scores": {"coding": 93, "reasoning": 87, "general_chat": 82, "tool_calling": 90, "agentic": 90}},
    {"match": ["gpt-5"],
     "tags": ["coding", "reasoning", "tool-calling", "long-context"],
     "good_for": "strong general frontier work: coding, analysis, agentic tasks",
     "reasoning_style": "adaptive router between fast and deliberate modes",
     "refine": False, "confidence": 0.55,
     "scores": {"coding": 90, "reasoning": 91, "general_chat": 90, "tool_calling": 89, "agentic": 88}},
    {"match": ["openai/o3", "o3-pro", "o3-mini"],
     "tags": ["reasoning", "coding"],
     "good_for": "hard math/logic and deep multi-step reasoning",
     "reasoning_style": "long-deliberation reasoner; slow but rigorous",
     "refine": False, "confidence": 0.55,
     "scores": {"coding": 88, "reasoning": 93, "general_chat": 84, "tool_calling": 84, "agentic": 85}},
    {"match": ["o4-mini"],
     "tags": ["reasoning", "coding"],
     "good_for": "cheap reasoning at volume",
     "reasoning_style": "compact deliberate reasoner",
     "refine": False, "confidence": 0.5,
     "scores": {"coding": 82, "reasoning": 85, "general_chat": 80, "tool_calling": 80, "agentic": 78}},
    {"match": ["gpt-4.1"],
     "tags": ["coding", "tool-calling", "long-context"],
     "good_for": "solid general coding and instruction-following, 1M context",
     "reasoning_style": "direct instruction-follower, minimal deliberation",
     "refine": False, "confidence": 0.55,
     "scores": {"coding": 84, "reasoning": 80, "general_chat": 84, "tool_calling": 85, "agentic": 80}},
    {"match": ["gpt-4o"],
     "tags": ["vision", "tool-calling"],
     "good_for": "multimodal chat, vision tasks, quick everyday answers",
     "reasoning_style": "fast conversational generalist",
     "refine": False, "confidence": 0.55,
     "scores": {"coding": 78, "reasoning": 76, "general_chat": 85, "tool_calling": 84, "agentic": 74}},
    {"match": ["gpt-oss"],
     "tags": ["reasoning", "tool-calling"],
     "good_for": "open-weight local/hosted reasoning at low cost",
     "reasoning_style": "open-weight reasoner with visible chain-of-thought",
     "refine": True, "confidence": 0.5,
     "scores": {"coding": 76, "reasoning": 80, "general_chat": 75, "tool_calling": 76, "agentic": 72}},

    # ---- Google -------------------------------------------------------------
    {"match": ["gemini-3"],
     "tags": ["coding", "reasoning", "vision", "tool-calling", "long-context"],
     "good_for": "frontier multimodal work with very long context",
     "reasoning_style": "strong all-rounder, particularly multimodal + long-context",
     "refine": False, "confidence": 0.5,
     "scores": {"coding": 91, "reasoning": 92, "general_chat": 91, "tool_calling": 88, "agentic": 88}},
    {"match": ["gemini-2.5-pro"],
     "tags": ["coding", "reasoning", "vision", "long-context"],
     "good_for": "long-document analysis (1M ctx), multimodal, strong general reasoning",
     "reasoning_style": "thinking-mode reasoner, excellent breadth",
     "refine": False, "confidence": 0.55,
     "scores": {"coding": 87, "reasoning": 89, "general_chat": 88, "tool_calling": 84, "agentic": 84}},
    {"match": ["gemini-2.5-flash", "gemini-2.0-flash", "gemini-flash"],
     "tags": ["vision", "long-context"],
     "good_for": "high-volume cheap multimodal chat and extraction",
     "reasoning_style": "fast and shallow; great throughput per dollar",
     "refine": True, "confidence": 0.55,
     "scores": {"coding": 78, "reasoning": 77, "general_chat": 83, "tool_calling": 79, "agentic": 74}},
    {"match": ["gemma3", "gemma-3", "gemma2", "gemma-2", "gemma"],
     "tags": [],
     "good_for": "light local chat and simple tasks on modest hardware",
     "reasoning_style": "small open model; concise, limited depth",
     "refine": True, "confidence": 0.5,
     "scores": {"coding": 58, "reasoning": 60, "general_chat": 70, "tool_calling": 55, "agentic": 48}},

    # ---- Meta ---------------------------------------------------------------
    {"match": ["llama-4", "llama4"],
     "tags": ["reasoning", "long-context", "vision"],
     "good_for": "open-weight general work, long context (MoE)",
     "reasoning_style": "open-weight generalist; wide context, mid-tier depth",
     "refine": True, "confidence": 0.5,
     "scores": {"coding": 76, "reasoning": 76, "general_chat": 82, "tool_calling": 74, "agentic": 70}},
    {"match": ["llama-3.3", "llama3.3"],
     "tags": ["tool-calling"],
     "good_for": "solid open 70B-class chat and light coding",
     "reasoning_style": "well-rounded open instruct model",
     "refine": True, "confidence": 0.55,
     "scores": {"coding": 72, "reasoning": 70, "general_chat": 78, "tool_calling": 75, "agentic": 66}},
    {"match": ["llama-3.2-90b-vision", "llama-3.2-11b-vision", "llama3.2-vision"],
     "tags": ["vision"],
     "good_for": "open-weight image understanding",
     "reasoning_style": "vision-instruct variant of Llama 3",
     "refine": True, "confidence": 0.5,
     "scores": {"coding": 55, "reasoning": 58, "general_chat": 68, "tool_calling": 55, "agentic": 45}},
    {"match": ["llama-3.1", "llama3.1", "llama-3-", "llama3:"],
     "tags": [],
     "good_for": "general open chat; large ecosystem of finetunes",
     "reasoning_style": "classic open instruct baseline",
     "refine": True, "confidence": 0.55,
     "scores": {"coding": 66, "reasoning": 65, "general_chat": 74, "tool_calling": 68, "agentic": 58}},

    # ---- Mistral ------------------------------------------------------------
    {"match": ["mistral-large"],
     "tags": ["coding", "tool-calling"],
     "good_for": "European-hosted strong generalist, good function calling",
     "reasoning_style": "efficient generalist, reliable structured output",
     "refine": False, "confidence": 0.55,
     "scores": {"coding": 78, "reasoning": 76, "general_chat": 80, "tool_calling": 81, "agentic": 74}},
    {"match": ["devstral"],
     "tags": ["coding", "tool-calling"],
     "good_for": "open-weight agentic coding (SWE-style tasks) on local hardware",
     "reasoning_style": "coding-agent specialist",
     "refine": True, "confidence": 0.55,
     "scores": {"coding": 80, "reasoning": 68, "general_chat": 62, "tool_calling": 78, "agentic": 78}},
    {"match": ["codestral"],
     "tags": ["coding"],
     "good_for": "fast code completion and generation",
     "reasoning_style": "code-completion specialist, minimal chat ability",
     "refine": True, "confidence": 0.55,
     "scores": {"coding": 78, "reasoning": 60, "general_chat": 55, "tool_calling": 62, "agentic": 55}},
    {"match": ["magistral"],
     "tags": ["reasoning"],
     "good_for": "open-weight deliberate reasoning",
     "reasoning_style": "chain-of-thought reasoner from Mistral",
     "refine": True, "confidence": 0.5,
     "scores": {"coding": 72, "reasoning": 79, "general_chat": 70, "tool_calling": 68, "agentic": 66}},
    {"match": ["pixtral"],
     "tags": ["vision"],
     "good_for": "open-weight vision + text",
     "reasoning_style": "multimodal Mistral variant",
     "refine": True, "confidence": 0.5,
     "scores": {"coding": 62, "reasoning": 64, "general_chat": 70, "tool_calling": 62, "agentic": 55}},
    {"match": ["mistral-small", "ministral", "mixtral", "mistral-nemo", "mistral:"],
     "tags": [],
     "good_for": "cheap fast general chat, light extraction",
     "reasoning_style": "compact efficient generalist",
     "refine": True, "confidence": 0.55,
     "scores": {"coding": 64, "reasoning": 62, "general_chat": 72, "tool_calling": 66, "agentic": 55}},

    # ---- Qwen (spans OpenRouter and the local fleet) --------------------------
    {"match": ["qwen3-coder", "qwen2.5-coder", "qwen-coder", "qwen3.5-coder", "qwen3.6-coder"],
     "tags": ["coding", "tool-calling"],
     "good_for": "open-weight coding workhorse; best local coding family",
     "reasoning_style": "code-specialized, strong repo-level competence for open weights",
     "refine": True, "confidence": 0.55,
     "scores": {"coding": 84, "reasoning": 72, "general_chat": 66, "tool_calling": 78, "agentic": 74}},
    {"match": ["qwq"],
     "tags": ["reasoning"],
     "good_for": "open-weight deep reasoning on local hardware",
     "reasoning_style": "long visible deliberation; slow but thorough for its size",
     "refine": True, "confidence": 0.55,
     "scores": {"coding": 74, "reasoning": 82, "general_chat": 68, "tool_calling": 66, "agentic": 64}},
    {"match": ["qwen3.6", "qwen3.5"],
     "tags": ["reasoning", "tool-calling"],
     "good_for": "current-gen open generalist; strong quality/size ratio locally",
     "reasoning_style": "hybrid thinking modes; well-rounded",
     "refine": True, "confidence": 0.45,
     "scores": {"coding": 78, "reasoning": 79, "general_chat": 78, "tool_calling": 77, "agentic": 72}},
    {"match": ["qwen3-vl", "qwen2.5-vl", "qwen-vl"],
     "tags": ["vision"],
     "good_for": "open-weight vision understanding, OCR, document images",
     "reasoning_style": "leading open multimodal family",
     "refine": True, "confidence": 0.55,
     "scores": {"coding": 60, "reasoning": 68, "general_chat": 70, "tool_calling": 62, "agentic": 55}},
    {"match": ["qwen3", "qwen2.5", "qwen"],
     "tags": ["tool-calling"],
     "good_for": "general open chat with solid multilingual + tool support",
     "reasoning_style": "balanced open generalist",
     "refine": True, "confidence": 0.55,
     "scores": {"coding": 72, "reasoning": 72, "general_chat": 75, "tool_calling": 74, "agentic": 64}},

    # ---- DeepSeek -------------------------------------------------------------
    {"match": ["deepseek-r1", "deepseek-reasoner"],
     "tags": ["reasoning", "coding"],
     "good_for": "open-weight frontier-adjacent reasoning; math, hard analysis",
     "reasoning_style": "extensive visible chain-of-thought; very strong reasoning per dollar",
     "refine": True, "confidence": 0.6,
     "scores": {"coding": 80, "reasoning": 88, "general_chat": 74, "tool_calling": 62, "agentic": 66}},
    {"match": ["deepseek-v3.2", "deepseek-v3.1"],
     "tags": ["coding", "reasoning", "tool-calling"],
     "good_for": "cheap near-frontier general + coding work",
     "reasoning_style": "efficient MoE generalist, improved agentic behavior in later revs",
     "refine": False, "confidence": 0.55,
     "scores": {"coding": 84, "reasoning": 82, "general_chat": 82, "tool_calling": 78, "agentic": 76}},
    {"match": ["deepseek-v3", "deepseek-chat", "deepseek"],
     "tags": ["coding", "reasoning"],
     "good_for": "cheap strong general/coding work",
     "reasoning_style": "efficient MoE generalist",
     "refine": True, "confidence": 0.55,
     "scores": {"coding": 82, "reasoning": 80, "general_chat": 80, "tool_calling": 72, "agentic": 70}},

    # ---- Chinese open labs ------------------------------------------------------
    {"match": ["glm-4.7", "glm-4.6", "glm-4.5", "glm-4", "glm-z1"],
     "tags": ["coding", "tool-calling"],
     "good_for": "open-weight agentic coding; strong tool use for the price",
     "reasoning_style": "agentic-coding oriented; good structured tool output",
     "refine": True, "confidence": 0.5,
     "scores": {"coding": 83, "reasoning": 78, "general_chat": 76, "tool_calling": 83, "agentic": 80}},
    {"match": ["kimi-k2", "moonshot"],
     "tags": ["coding", "tool-calling"],
     "good_for": "open-weight agentic work and coding at low cost",
     "reasoning_style": "large MoE tuned specifically for agentic tool use",
     "refine": False, "confidence": 0.5,
     "scores": {"coding": 84, "reasoning": 80, "general_chat": 80, "tool_calling": 86, "agentic": 84}},
    {"match": ["minimax-m2", "minimax"],
     "tags": ["coding", "tool-calling"],
     "good_for": "cheap open agentic coding",
     "reasoning_style": "compact-activation MoE aimed at agent loops",
     "refine": True, "confidence": 0.45,
     "scores": {"coding": 82, "reasoning": 78, "general_chat": 74, "tool_calling": 82, "agentic": 80}},
    {"match": ["yi-", "01-ai"],
     "tags": [],
     "good_for": "general open chat",
     "reasoning_style": "earlier-gen open generalist",
     "refine": True, "confidence": 0.45,
     "scores": {"coding": 60, "reasoning": 62, "general_chat": 68, "tool_calling": 58, "agentic": 50}},

    # ---- xAI / Cohere / others ---------------------------------------------------
    {"match": ["grok-code"],
     "tags": ["coding", "tool-calling"],
     "good_for": "fast agentic coding",
     "reasoning_style": "speed-focused coding agent model",
     "refine": False, "confidence": 0.5,
     "scores": {"coding": 84, "reasoning": 78, "general_chat": 74, "tool_calling": 82, "agentic": 80}},
    {"match": ["grok-4", "grok-3", "grok"],
     "tags": ["reasoning", "tool-calling"],
     "good_for": "frontier general reasoning, current-events tone",
     "reasoning_style": "deliberate reasoner, strong math/logic",
     "refine": False, "confidence": 0.5,
     "scores": {"coding": 84, "reasoning": 87, "general_chat": 83, "tool_calling": 82, "agentic": 80}},
    {"match": ["command-a", "command-r", "cohere"],
     "tags": ["tool-calling"],
     "good_for": "RAG-grounded enterprise answers and tool use",
     "reasoning_style": "retrieval-grounded, citation-friendly",
     "refine": True, "confidence": 0.5,
     "scores": {"coding": 68, "reasoning": 68, "general_chat": 76, "tool_calling": 76, "agentic": 62}},
    {"match": ["phi-4", "phi4"],
     "tags": ["reasoning"],
     "good_for": "small-footprint reasoning; strong for a 14B",
     "reasoning_style": "textbook-trained small reasoner",
     "refine": True, "confidence": 0.5,
     "scores": {"coding": 64, "reasoning": 71, "general_chat": 66, "tool_calling": 58, "agentic": 50}},
    {"match": ["phi-3", "phi3", "phi:"],
     "tags": [],
     "good_for": "very light local tasks",
     "reasoning_style": "small model, shallow but fast",
     "refine": True, "confidence": 0.5,
     "scores": {"coding": 52, "reasoning": 56, "general_chat": 60, "tool_calling": 45, "agentic": 38}},
    {"match": ["nemotron"],
     "tags": ["reasoning", "tool-calling"],
     "good_for": "open-weight reasoning/agentic (NVIDIA-tuned Llama)",
     "reasoning_style": "RL-polished Llama derivative",
     "refine": True, "confidence": 0.45,
     "scores": {"coding": 72, "reasoning": 77, "general_chat": 74, "tool_calling": 74, "agentic": 68}},
    {"match": ["amazon/nova", "nova-pro", "nova-lite", "nova-micro"],
     "tags": ["vision"],
     "good_for": "cheap AWS-native multimodal chat",
     "reasoning_style": "cost-optimized generalist",
     "refine": True, "confidence": 0.45,
     "scores": {"coding": 66, "reasoning": 64, "general_chat": 72, "tool_calling": 68, "agentic": 56}},

    # ---- Local-fleet specialists (bare Ollama tags) --------------------------------
    {"match": ["ornith"],
     "tags": ["tool-calling", "reasoning"],
     "good_for": "routing/dispatch brain: reliable structured tool calls at small size",
     "reasoning_style": "self-scaffolding tool-caller; terse, decision-oriented",
     "refine": False, "confidence": 0.5,
     "scores": {"coding": 62, "reasoning": 72, "general_chat": 64, "tool_calling": 85, "agentic": 80}},
    {"match": ["hermes", "openhermes"],
     "tags": ["tool-calling"],
     "good_for": "local function calling and structured JSON output",
     "reasoning_style": "instruction-tuned for schema-following",
     "refine": True, "confidence": 0.5,
     "scores": {"coding": 62, "reasoning": 62, "general_chat": 68, "tool_calling": 76, "agentic": 60}},
    {"match": ["llava", "bakllava"],
     "tags": ["vision"],
     "good_for": "basic local image description/Q&A",
     "reasoning_style": "classic open VLM; dated but serviceable",
     "refine": True, "confidence": 0.55,
     "scores": {"coding": 30, "reasoning": 45, "general_chat": 55, "tool_calling": 30, "agentic": 25}},
    {"match": ["moondream"],
     "tags": ["vision"],
     "good_for": "tiny fast local image captioning",
     "reasoning_style": "minimal VLM, speed over depth",
     "refine": True, "confidence": 0.5,
     "scores": {"coding": 15, "reasoning": 30, "general_chat": 40, "tool_calling": 15, "agentic": 12}},
    {"match": ["starcoder", "codellama", "codegemma", "codeqwen"],
     "tags": ["coding"],
     "good_for": "local code completion (previous generation)",
     "reasoning_style": "completion-oriented, weak at chat/instructions",
     "refine": True, "confidence": 0.55,
     "scores": {"coding": 58, "reasoning": 42, "general_chat": 38, "tool_calling": 35, "agentic": 28}},
    {"match": ["dolphin"],
     "tags": [],
     "good_for": "permissive local chat (uncensored finetune family)",
     "reasoning_style": "compliance-tuned finetunes of open bases; quality tracks the base model",
     "refine": True, "confidence": 0.5,
     "scores": {"coding": 60, "reasoning": 60, "general_chat": 68, "tool_calling": 55, "agentic": 48}},
    {"match": ["granite"],
     "tags": ["tool-calling"],
     "good_for": "enterprise-flavored local tasks, decent function calling",
     "reasoning_style": "IBM's conservative open family",
     "refine": True, "confidence": 0.45,
     "scores": {"coding": 60, "reasoning": 60, "general_chat": 66, "tool_calling": 70, "agentic": 52}},
    {"match": ["smollm", "tinyllama", "tinydolphin"],
     "tags": [],
     "good_for": "experiments on tiny hardware only",
     "reasoning_style": "sub-3B; expect frequent mistakes",
     "refine": True, "confidence": 0.6,
     "scores": {"coding": 20, "reasoning": 25, "general_chat": 38, "tool_calling": 15, "agentic": 10}},
    {"match": ["wizardlm", "vicuna", "openchat", "zephyr", "starling", "solar",
               "orca", "neural-chat", "stablelm", "falcon"],
     "tags": [],
     "good_for": "legacy open chat finetunes; superseded by current families",
     "reasoning_style": "previous-generation instruct tunes",
     "refine": True, "confidence": 0.5,
     "scores": {"coding": 45, "reasoning": 48, "general_chat": 58, "tool_calling": 35, "agentic": 28}},
]
